### ISSUE TITLE
Can you drop the project URL here?

### ISSUE THREAD

**Issue by HarshClinikally** [LazyCodeer/Clinikally#1]

**Comment by LazyCodeer** [comment]
# Instructions to Run the Expo App "Clinikally"

Here are the steps to set up and run the Expo app "Clinikally Done" on your device.

## Prerequisites

1. **Install Expo Go:**

   - First, download and install the Expo Go app from the Google Play Store:
     - [Expo Go on Google Play Store](https://play.google.com/store/apps/details?id=host.exp.exponent&pcampaignid=web_share)

2. **Access the Project:**
   - You can view the project hosted on Expo using the link below:
     - [Clinikally Done Project](https://expo.dev/preview/update?message=clinikally&updateRuntimeVersion=1.0.0&createdAt=2024-10-27T10%3A27%3A52.675Z&slug=exp&projectId=37e1b7ff-6b57-4931-8f05-61ebb8fb21bf&group=8719a58f-1e27-417b-b845-23ee9d6ead50)

## Steps to Run the App

1. **Open Expo Go:**

   - Launch the Expo Go app on your mobile device.
![image](https://github.com/user-attachments/assets/f68259e1-5ca8-480f-81c3-392f17469848)

2. **Scan the QR Code:**

   - In the Expo Go app, tap on "Scan QR Code." You might need to allow the app to access your camera..

3. **Wait for Loading:**
   - The app should load, and you’ll be able to start using "Clinikally"
